AR = '/opt/openwrt/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-5.3.0_musl-1.1.14_eabi/bin/arm-openwrt-linux-muslgnueabi-ar'
ARFLAGS = 'rcs'
BINDIR = '/usr/bin'
BOOST_VERSION = '1_61'
CC = ['/usr/bin/gcc']
CCLNK_SRC_F = []
CCLNK_TGT_F = ['-o']
CC_NAME = 'gcc'
CC_SRC_F = []
CC_TGT_F = ['-c', '-o']
CC_VERSION = ('5', '3', '0')
CFLAGS = ['-I/opt/openwrt/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl-1.1.14_eabi/usr/include', '-I/opt/openwrt/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl-1.1.14_eabi/usr/include']
CFLAGS_MACBUNDLE = ['-fPIC']
CFLAGS_cshlib = ['-fPIC']
COMPILER_CC = 'gcc'
COMPILER_CXX = 'g++'
CPPPATH_ST = '-I%s'
CXX = ['/opt/openwrt/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-5.3.0_musl-1.1.14_eabi/bin/arm-openwrt-linux-muslgnueabi-g++']
CXXFLAGS = ['-I/opt/openwrt/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl-1.1.14_eabi/usr/include', '-O2', '-O3', '-std=c++11', '-std=c++0x', '-D_WEBSOCKETPP_CPP11_STL_', '-g']
CXXFLAGS_MACBUNDLE = ['-fPIC']
CXXFLAGS_cxxshlib = ['-fPIC']
CXXLNK_SRC_F = []
CXXLNK_TGT_F = ['-o']
CXX_NAME = 'gcc'
CXX_SRC_F = []
CXX_TGT_F = ['-c', '-o']
DEFINES_ST = '-D%s'
DEST_BINFMT = 'elf'
DEST_CPU = 'arm'
DEST_OS = 'linux'
INCLUDES_BOOST = '/opt/openwrt/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl-1.1.14_eabi/usr/include'
LIBDIR = '/usr/lib'
LIBPATH_BOOST = ['/opt/openwrt/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl-1.1.14_eabi/usr/lib']
LIBPATH_ST = '-L%s'
LIB_BOOST = ['boost_system']
LIB_ST = '-l%s'
LINKFLAGS = ['-L/opt/openwrt/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl-1.1.14_eabi/usr/lib', '-L/opt/openwrt/openwrt/staging_dir/target-arm_cortex-a9+vfpv3_musl-1.1.14_eabi/usr/lib']
LINKFLAGS_MACBUNDLE = ['-bundle', '-undefined', 'dynamic_lookup']
LINKFLAGS_cshlib = ['-shared']
LINKFLAGS_cstlib = ['-Wl,-Bstatic']
LINKFLAGS_cxxshlib = ['-shared']
LINKFLAGS_cxxstlib = ['-Wl,-Bstatic']
LINK_CC = ['/usr/bin/gcc']
LINK_CXX = ['/opt/openwrt/openwrt/staging_dir/toolchain-arm_cortex-a9+vfpv3_gcc-5.3.0_musl-1.1.14_eabi/bin/arm-openwrt-linux-muslgnueabi-g++']
PREFIX = '/usr'
RPATH_ST = '-Wl,-rpath,%s'
SHLIB_MARKER = '-Wl,-Bdynamic'
SONAME_ST = '-Wl,-h,%s'
STLIBPATH_ST = '-L%s'
STLIB_MARKER = '-Wl,-Bstatic'
STLIB_ST = '-l%s'
cprogram_PATTERN = '%s'
cshlib_PATTERN = 'lib%s.so'
cstlib_PATTERN = 'lib%s.a'
cxxprogram_PATTERN = '%s'
cxxshlib_PATTERN = 'lib%s.so'
cxxstlib_PATTERN = 'lib%s.a'
macbundle_PATTERN = '%s.bundle'
