version: '3'
services:
  notebook:
    image: jupyter/datascience-notebook
    build: .
    shm_size: '10gb'
    cap_add:
      - ALL
    container_name: dissertation-notebook
    ports:
      - 8888:8888
    environment:
      - GRANT_SUDO:'yes'
    volumes:
      - data:/home/jovyan/data/results:nocopy
      - gfx:/home/jovyan/gfx:nocopy
    command: start.sh jupyter lab --NotebookApp.iopub_data_rate_limit=10000000000 --NotebookApp.token='' --NotebookApp.password=''

# that the important thing
volumes:
  gfx:
    ../gfx
  data:
    ../results