language: python
sudo: required

matrix:
  include:
    - dist: trusty
      env: dist="14.04 LTS trusty"
    - dist: xenial
      env: dist="16.04 LTS xenial"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get -qq update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y install ansible libffi-dev libssl-dev

install:
  - cd ansible; sudo ansible-playbook -i "localhost," -c local -v install.yml; cd ..

script:
  - sudo py.test -v mininet/test/test_containernet.py
