#!/bin/sh /etc/rc.common

USE_PROCD=1
START=10
STOP=15

start_service() {
  procd_open_instance
  procd_set_param command /ndn/nfd --config /etc/ndn/nfd.conf.sample

  # respawn automatically if something died, be careful if you have an alternative process supervisor
  # if process dies sooner than respawn_threshold, it is considered crashed and after 5 retries the service is stopped
  procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5}

  procd_set_param limits core="unlimited"  # If you need to set ulimit for your process
  procd_set_param stdout 1 # forward stdout of the command to logd
  procd_set_param stderr 1 # same for stderr
  #procd_set_param user nobody # run service as user nobody
  procd_close_instance
}

reload_service()
{
        echo "Explicitly restarting service, are you sure you need this?"
        stop
        start
}
