#! /bin/sh
### BEGIN INIT INFO
# Provides: ndn
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: ndn
# Description: This file starts and stops ndn
#
### END INIT INFO

HOME=/home/kom

case "$1" in
 start)
   $HOME/start_ndn_fs.sh
   ;;
 stop)
   killall ndnfs-server
   sleep 10
   ;;
 restart)
   killall ndnfs-server
   sleep 20
   $HOME/start_ndn_fs.sh
   ;;
 *)
   echo "Usage: ndn {start|stop|restart}" >&2
   exit 3
   ;;
esac
