version: '2'
services:
  ndn:
    build:
      context: .
    tty: true
    stdin_open: true
    network_mode: "bridge"
    privileged: true
    #volumes:
    # - ../../dash:/videos
    container_name: ndn-dash
    cap_add:
      - NET_ADMIN
    ports:
     #- 80:80
     - 9696:9696
     - 6363:6363
